/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author User
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public AddItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSlider1 = new javax.swing.JSlider();
        jPanelRight = new javax.swing.JPanel();
        PasswordInter1 = new javax.swing.JLabel();
        RegName1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PasswordInter = new javax.swing.JLabel();
        RegName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        SignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRight.setBackground(new java.awt.Color(135, 191, 255));
        jPanelRight.setPreferredSize(new java.awt.Dimension(800, 510));
        jPanelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordInter1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        PasswordInter1.setForeground(new java.awt.Color(255, 255, 255));
        PasswordInter1.setText("Name");
        jPanelRight.add(PasswordInter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        RegName1.setBackground(new java.awt.Color(135, 191, 255));
        RegName1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        RegName1.setForeground(new java.awt.Color(255, 255, 255));
        RegName1.setBorder(null);
        RegName1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegName1ActionPerformed(evt);
            }
        });
        jPanelRight.add(RegName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 300, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 300, 5));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelRight.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 140, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipe :");
        jLabel3.setToolTipText("");
        jPanelRight.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 300, 5));

        PasswordInter.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        PasswordInter.setForeground(new java.awt.Color(255, 255, 255));
        PasswordInter.setText("Harga :");
        jPanelRight.add(PasswordInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        RegName.setBackground(new java.awt.Color(135, 191, 255));
        RegName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        RegName.setForeground(new java.awt.Color(255, 255, 255));
        RegName.setBorder(null);
        RegName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNameActionPerformed(evt);
            }
        });
        jPanelRight.add(RegName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 300, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 300, 5));

        SignUp.setBackground(new java.awt.Color(173, 215, 246));
        SignUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanelRight.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 100, 40));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Item");
        jPanelRight.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 510, 500));

        email.setBackground(new java.awt.Color(173, 215, 246));
        email.setToolTipText("");
        email.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/item.png"))); // NOI18N
        email.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 200));

        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegName1ActionPerformed

    private void RegNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegNameActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) { 
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Register().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordInter;
    private javax.swing.JLabel PasswordInter1;
    private javax.swing.JTextField RegName;
    private javax.swing.JTextField RegName1;
    private javax.swing.JButton SignUp;
    private javax.swing.JPanel email;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

    


}
