/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author User
 */
public class AddTickets extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public AddTickets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSlider1 = new javax.swing.JSlider();
        jPanelRight = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PasswordInter = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jComboBoxtipe = new javax.swing.JComboBox<>();
        harga = new javax.swing.JTextField();
        email = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRight.setBackground(new java.awt.Color(135, 191, 255));
        jPanelRight.setPreferredSize(new java.awt.Dimension(800, 510));
        jPanelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Ticket");
        jPanelRight.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipe :");
        jLabel3.setToolTipText("");
        jPanelRight.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 300, 5));

        PasswordInter.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        PasswordInter.setForeground(new java.awt.Color(255, 255, 255));
        PasswordInter.setText("Harga :");
        jPanelRight.add(PasswordInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 300, 5));

        add.setBackground(new java.awt.Color(173, 215, 246));
        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanelRight.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, 40));

        jComboBoxtipe.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jComboBoxtipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiket Kereta", "Tiket Pesawat", "Tiket Bus" }));
        jComboBoxtipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtipeActionPerformed(evt);
            }
        });
        jPanelRight.add(jComboBoxtipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, -1));

        harga.setBackground(new java.awt.Color(135, 191, 255));
        harga.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setBorder(null);
        harga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanelRight.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 300, -1));

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 510, 500));

        email.setBackground(new java.awt.Color(173, 215, 246));
        email.setToolTipText("");
        email.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/tiket.png"))); // NOI18N
        email.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 200));

        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void jComboBoxtipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtipeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) { 
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Register().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordInter;
    private javax.swing.JButton add;
    private javax.swing.JPanel email;
    private javax.swing.JTextField harga;
    private javax.swing.JComboBox<String> jComboBoxtipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the add
     */
    public javax.swing.JButton getAdd() {
        return add;
    }

    /**
     * @return the harga
     */
    public javax.swing.JTextField getHarga() {
        return harga;
    }

    /**
     * @return the jComboBoxtipe
     */
    public javax.swing.JComboBox<String> getjComboBoxtipe() {
        return jComboBoxtipe;
    }

    public void addlistener(ActionListener a){
        add.addActionListener(a);
    } 


}
