/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerLoginCustomer;
import javax.swing.JFrame;

/**
 *
 * @author Dimas
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lcus = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        Lsell = new javax.swing.JLabel();
        LiconCus = new javax.swing.JLabel();
        LiconSel = new javax.swing.JLabel();
        bacground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(173, 215, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lcus.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        Lcus.setForeground(new java.awt.Color(255, 255, 255));
        Lcus.setText("Customers");
        Lcus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LcusMouseClicked(evt);
            }
        });
        jPanel1.add(Lcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        welcome.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        Lsell.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        Lsell.setForeground(new java.awt.Color(255, 255, 255));
        Lsell.setText("Seller");
        Lsell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lsell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LsellMouseClicked(evt);
            }
        });
        jPanel1.add(Lsell, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        LiconCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/009-money-1.png"))); // NOI18N
        LiconCus.setText("jLabel6");
        LiconCus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LiconCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LiconCusMouseClicked(evt);
            }
        });
        jPanel1.add(LiconCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 190, -1));

        LiconSel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/017-jacket.png"))); // NOI18N
        LiconSel.setText("jLabel1");
        LiconSel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LiconSel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LiconSelMouseClicked(evt);
            }
        });
        jPanel1.add(LiconSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 190, -1));

        bacground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/coba2.png"))); // NOI18N
        bacground.setText("jLabel2");
        jPanel1.add(bacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LiconCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LiconCusMouseClicked
        // TODO add your handling code here:
<<<<<<< HEAD
        LoginCustomer loginCus = new LoginCustomer();
        loginCus.setVisible(true);
        loginCus.pack();
        loginCus.setLocationRelativeTo(null);
        loginCus.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
=======
        new ControllerLoginCustomer();
>>>>>>> 387f36ab523d8b7ef6bceb302fb9f8cf6e6c4aef
        this.dispose();
    }//GEN-LAST:event_LiconCusMouseClicked

    private void LcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LcusMouseClicked
        // TODO add your handling code here:
        new ControllerLoginCustomer();
        this.dispose();
    }//GEN-LAST:event_LcusMouseClicked

    private void LiconSelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LiconSelMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        brandOrPersonal barnd_personal = new brandOrPersonal();
        barnd_personal.setVisible(true);
        barnd_personal.pack();
        barnd_personal.setLocationRelativeTo(null);
        barnd_personal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LiconSelMouseClicked

    private void LsellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LsellMouseClicked
        // TODO add your handling code here:
        brandOrPersonal barnd_personal = new brandOrPersonal();
        barnd_personal.setVisible(true);
        barnd_personal.pack();
        barnd_personal.setLocationRelativeTo(null);
        barnd_personal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LsellMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Beranda().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcus;
    private javax.swing.JLabel LiconCus;
    private javax.swing.JLabel LiconSel;
    private javax.swing.JLabel Lsell;
    private javax.swing.JLabel bacground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
