/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import static javax.swing.text.html.HTML.Tag.HEAD;

/**
 *
 * @author User
 */
public class SignUpCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public SignUpCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSlider1 = new javax.swing.JSlider();
        jPanelRight = new javax.swing.JPanel();
        dolpick = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        RegName = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        RegPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        RegAddress = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        Regemail = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        SignUp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRight.setBackground(new java.awt.Color(135, 191, 255));
        jPanelRight.setPreferredSize(new java.awt.Dimension(800, 510));
        jPanelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dolpick.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        dolpick.setForeground(new java.awt.Color(255, 255, 255));
        dolpick.setText("DolPick.com");
        jPanelRight.add(dolpick, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        signup.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("Sign Up Customer");
        jPanelRight.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name :");
        name.setToolTipText("");
        jPanelRight.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        RegName.setBackground(new java.awt.Color(135, 191, 255));
        RegName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        RegName.setForeground(new java.awt.Color(255, 255, 255));
        RegName.setBorder(null);
        RegName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNameActionPerformed(evt);
            }
        });
        jPanelRight.add(RegName, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 162, 300, -1));

        Password.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password :");
        jPanelRight.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        RegPassword.setBackground(new java.awt.Color(135, 191, 255));
        RegPassword.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        RegPassword.setForeground(new java.awt.Color(255, 255, 255));
        RegPassword.setBorder(null);
        jPanelRight.add(RegPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 300, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address :");
        jPanelRight.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        RegAddress.setBackground(new java.awt.Color(135, 191, 255));
        RegAddress.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        RegAddress.setForeground(new java.awt.Color(255, 255, 255));
        RegAddress.setBorder(null);
        RegAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegAddressActionPerformed(evt);
            }
        });
        jPanelRight.add(RegAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 300, -1));

        email.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        jPanelRight.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        Regemail.setBackground(new java.awt.Color(135, 191, 255));
        Regemail.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        Regemail.setForeground(new java.awt.Color(255, 255, 255));
        Regemail.setBorder(null);
        Regemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegemailActionPerformed(evt);
            }
        });
        jPanelRight.add(Regemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 300, -1));

        jCheckBox1.setBackground(new java.awt.Color(135, 191, 255));
        jCheckBox1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("I accept the terms in the license agreement");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanelRight.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        SignUp.setBackground(new java.awt.Color(173, 215, 246));
        SignUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanelRight.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 100, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 300, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 300, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 300, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 300, 5));

        getContentPane().add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 510, 670));

        jPanelLeft.setBackground(new java.awt.Color(173, 215, 246));
        jPanelLeft.setToolTipText("");
        jPanelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/login.png"))); // NOI18N
        jPanelLeft.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 130, 200));

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void RegemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegemailActionPerformed

    private void RegAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegAddressActionPerformed

    private void RegNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegNameActionPerformed

    /**
     * @param args the command line arguments
     */
//<<<<<<< HEAD:~Proyek Besar Tubes PBO~/~Proyek Besar Tubes PBO~/TUBES Net/T_Ne_tV0.1Apple/src/View/Register.java
//    public static void main(String args[]) {
//=======
//    public static void main(String args[]) { 
//>>>>>>> ca00af0c9ae460c2d8c0f589331bbc8004a10c69:~Proyek Besar Tubes PBO~/~Proyek Besar Tubes PBO~/TUBES Net/T_Ne_tV0.1Apple/src/View/SignUpCustomer.java
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Register().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JTextField RegAddress;
    private javax.swing.JTextField RegName;
    private javax.swing.JPasswordField RegPassword;
    private javax.swing.JTextField Regemail;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel dolpick;
    private javax.swing.JLabel email;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JLabel signup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the RegAddress
     */
    public javax.swing.JTextField getRegAddress() {
        return RegAddress;
    }

    /**
     * @param RegAddress the RegAddress to set
     */
    public void setRegAddress(javax.swing.JTextField RegAddress) {
        this.RegAddress = RegAddress;
    }

    /**
     * @return the RegName
     */
    public javax.swing.JTextField getRegName() {
        return RegName;
    }

    /**
     * @param RegName the RegName to set
     */
    public void setRegName(javax.swing.JTextField RegName) {
        this.RegName = RegName;
    }

    /**
     * @return the RegPassword
     */
    public javax.swing.JPasswordField getRegPassword() {
        return RegPassword;
    }

    /**
     * @param RegPassword the RegPassword to set
     */
    public void setRegPassword(javax.swing.JPasswordField RegPassword) {
        this.RegPassword = RegPassword;
    }

    /**
     * @return the Regemail
     */
    public javax.swing.JTextField getRegemail() {
        return Regemail;
    }

    /**
     * @param Regemail the Regemail to set
     */
    public void setRegemail(javax.swing.JTextField Regemail) {
        this.Regemail = Regemail;
    }

    /**
     * @return the SignUp
     */
    public javax.swing.JButton getSignUp() {
        return SignUp;
    }

    /**
     * @param SignUp the SignUp to set
     */
    public void setSignUp(javax.swing.JButton SignUp) {
        this.SignUp = SignUp;
    }


    public void addlistener(ActionListener e){
        SignUp.addActionListener(e);
    }
    

}
